### ISSUE TITLE
Porting Components in mcs-lite-ui

### ISSUE THREAD

**Issue by liuderchi** [Mediatek-Cloud/mcs-ui#9]
Those draggable items are [mcs-lite-ui](https://mcs-lite-ui.netlify.com/) components being used frequently while
they are not yet implemented in mcs-ui.

- [x] `Avatar` (/lib/Avatar/Avatar) → #14
- [x] `Breadcrumb` (/lib/Breadcrumb/Breadcrumb)
- [ ] ~~`CopyButton` (/lib/CopyButton/CopyButton)~~ (Pending Oct 24)
- [x] `Dialog` (/lib/Dialog/Dialog) → `react-overlay-pack`
- [x] `emptyFunction` (/lib/utils/emptyFunction) → #20
- [x] `Hr` (/lib/Hr/Hr) → #20
- [x] `IconCheck` (/lib/Checkbox/IconCheck)
- [x] `IconWarning` (/lib/IconWarning/IconWarning)
- [x] `ImageDropzone` (/lib/ImageDropzone/ImageDropzone) → #25
- [x] `InputMultiSelect` (/lib/InputMultiSelect/InputMultiSelect) → #28
- [x] `InputOrder` (/lib/InputOrder/InputOrder) → #28
- [x] `MCS` (/lib/Logo/MCS) → `/Logo/LogoMCS` #36
- [x] `PanelIcon` (/lib/PanelIcon/PanelIcon) → #36
- [x] `StatusLight` (/lib/StatusLight/StatusLight) → #36
- [x] `Switch` (/lib/Switch/Switch) → #36
- [x] `Tooltip` (/lib/Tooltip/Tooltip) → #36

**Comment by liuderchi** [comment]
Congrats for v1.0 🎉
